#!/bin/bash

set -m # Enable Job Control

sizes=("2" "3" "4" "5" "7" "10" "15" "20" "25" "30" "40" "50" "70" "100")

methods=('-b' '-c')

for method in ${methods[@]}
do
  for (( idx=${#sizes[@]}-1 ; idx>=0 ; idx-- ))
  do
    echo "${sizes[idx]}"
    while [ "$(jobs | wc -l)" -ge 3 ]
    do
      sleep 5
    done
    ./schaeferTurek.py -s ${sizes[idx]} -r 100 $method &
  done
done
while [ 1 ]
do
  fg &> /dev/null
  [ $? == 1 ] && break
  sleep 1
done
