#!/bin/bash

set -m # Enable Job Control

lengths=("3" "5" "7" "9" "11" "15" "20" "25" "30" "35" "40" "45" "50" "60" "70" "80" "90" "100")

methods=('\ ' '-c')

for length in ${lengths[@]}
do
  for method in ${methods[@]}
  do
    while [ "$(jobs | wc -l)" -ge 3 ]
    do
      sleep 5
    done
    ./poiseuille.py -l $length $method &
  done
done
while [ 1 ]
do
  fg &> /dev/null
  [ $? == 1 ] && break
  sleep 1
done
