#!/bin/bash

set -m # Enable Job Control

lengths=("100" "95" "90" "85" "80" "75" "70" "65" "60" "55" "50" "45" "40" "35" "30" "25" "20" "15" "11" "9" "7" "5" "3")

methods=('\ ' '-c')

for length in ${lengths[@]}
do
  for method in ${methods[@]}
  do
    while [ "$(jobs | wc -l)" -ge 7 ]
    do
      sleep 0.5
    done
    ./poiseuille.py -l $length $method &
  done
done
while [ 1 ]
do
  fg &> /dev/null
  [ $? == 1 ] && break
  sleep 1
done
