#!/bin/bash
# 2D Lattice Boltzmann Code
# Copyright (C) 2016  Florian Rohm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -m # Enable Job Control

sizes=("50" "45" "40" "35" "30" "28" "26" "24" "22" "20" "18" "16" "14" "12" "10" "9" "8" "7" "6" "5" "4" "3")

methods=('\ ' '-c')

for size in ${sizes[@]}
do
  for method in ${methods[@]}
  do
    while [ "$(jobs | wc -l)" -ge 7 ]
    do
      sleep 5
    done
    ./schaeferTurek.py -s $size -r 100 $method &
  done
done
while [ 1 ]
do
  fg &> /dev/null
  [ $? == 1 ] && break
  sleep 1
done
