#!/bin/bash
# 2D Lattice Boltzmann Code
# Copyright (C) 2016  Florian Rohm
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -m # Enable Job Control

#sizes=("256" "192" "128" "96")
sizes=( "96")

#reynolds=("100000" "10000" "5000" "2000" "1000")
reynolds=("6400" "6300" "6200" "6100")

methods=('\ ' '-c')

for size in ${sizes[@]}
do
  for re in ${reynolds[@]}
  do
    for method in ${methods[@]}
    do
      while [ "$(jobs | wc -l)" -ge 6 ]
      do
        sleep 5
      done
      ./vortexMerge.py -s $size -r $re $method &
    done
  done
done
while [ 1 ]
do
  fg &> /dev/null
  [ $? == 1 ] && break
  sleep 1
done
